development:
  adapter: postgresql
  database: prelaunchr_development
  
 

test:
  adapter: postgresql
  database: prelaunchr_test
 

production:
  adapter: postgresql
  database: prelauncr_production
  host: ec2-23-21-220-167.compute-1.amazonaws.com
  port: 5432
