development:
  adapter: postgresql
  database: prelaunchr_development
  
 

test:
  adapter: postgresql
  database: prelaunchr_test
 

production:
  adapter: postgresql
  database: d5aupfmt919q68
  host: ec2-23-21-220-167.compute-1.amazonaws.com
  port: 5432
  user: ovjqfmxeyjjrbn
  password: fbd8e8d350829d408546718c7f701bc09d0502b3df1f0faa6fd40ac6fc98885b
