development:
  adapter: postgresql
  database: prelaunchr_development
  
 

test:
  adapter: postgresql
  database: prelaunchr_test
 

production:
  adapter: postgresql
  database: prelauncr_production
  host: localhost
  port: 5432
